#!/bin/bash
if [ $# -ne "2" ]; then
	echo " ./create target_app_name  apps  "
	echo -e "\n\n"
	echo "               example       "
	echo -e "\n\n"
	echo " ./create tag twr_tag"
	echo -e "\n"
	exit 1
fi
#newt target create $1
#newt target set $1 app=@apache-mynewt-core/apps/$2 
#newt target set $1 bsp=@apache-mynewt-core/hw/bsp/$5
#newt target set $1 build_profile=optimized

if [ $2 == "boot" ]; then
newt target create $1
newt target set $1 app=@apache-mynewt-core/apps/$2
newt target set $1 bsp=@apache-mynewt-core/hw/bsp/dwm1001-dev
newt target set $1 build_profile=optimized
newt target show $1
else
newt target create $1
newt target set $1 app=apps/$2
newt target set $1 bsp=@apache-mynewt-core/hw/bsp/dwm1001-dev
newt target set $1 build_profile=debug
newt target show $1
fi
#mkdir $1
#newt build nrf52840pdk_boot
#newt build nrf52840pdk_blinky
#newt create-image nrf52840pdk_blinky 1.0.0
